tasks:
  - init: sudo apt update && sudo apt upgrade -y && sudo apt install graphviz -y && virtualenv venv && source venv/bin/activate && python -m pip install --upgrade pip && pip install -r requirements.txt


